const GET_BOOKS = "GET_BOOKS"; 
const SET_BOOKS = "SET_BOOKS"; 
const ADD_BOOKS = "ADD_BOOKS"; 
const LOAD_BOOKS = "LOAD_BOOKS"; 
const SET_FILTER = "SET_FILTER"

export {GET_BOOKS, SET_BOOKS, ADD_BOOKS, LOAD_BOOKS, SET_FILTER}